[package]
name         = "stash-clipboard"
description  = "Wayland clipboard manager with fast persistent history and multi-media support"
version      = "0.4.0"
edition      = "2024"
authors      = [ "NotAShelf <raf@notashelf.dev>" ]
license      = "MPL-2.0"
readme       = true
repository   = "https://github.com/notashelf/stash"
rust-version = "1.95.0"

[[bin]]
name = "stash"       # actual binary name for Nix, Cargo, etc.
path = "src/main.rs"

[dependencies]
age                   = { version = "0.12.1", optional = true }
arc-swap              = { version = "1.9.2", optional = true }
base64                = "0.22.1"
blocking              = "1.6.2"
clap                  = { version = "4.6.3", features = [ "derive", "env" ] }
clap-verbosity-flag   = "3.0.4"
color-eyre            = "0.6.5"
crossterm             = "0.29.0"
ctrlc                 = "3.5.2"
dirs                  = "6.0.0"
env_logger            = "0.11.11"
humantime             = "2.4.0"
imagesize             = "0.15.0"
inquire               = { version = "0.9.4", default-features = false, features = [ "crossterm" ] }
libc                  = "0.2.188"
log                   = "0.4.33"
mime-sniffer          = "0.1.3"
notify-rust           = { version = "4.18.0", optional = true }
ratatui               = "0.30.2"
regex                 = "1.13.1"
rusqlite              = { version = "0.40.1", features = [ "bundled" ] }
serde                 = { version = "1.0.229", features = [ "derive" ] }
serde_json            = "1.0.151"
smol                  = "2.0.2"
thiserror             = "2.0.19"
unicode-segmentation  = "1.13.3"
unicode-width         = "0.2.2"
wayland-client        = { version = "0.31.14", features = [ "log" ], optional = true }
wayland-protocols-wlr = { version = "0.3.12", default-features = false, optional = true }
wl-clipboard-rs       = "0.9.3"

[dev-dependencies]
futures  = "0.3.33"
tempfile = "3.27.0"

[features]
default       = [ "notifications", "use-toplevel", "encryption" ]
encryption    = [ "dep:age" ]
notifications = [ "dep:notify-rust" ]
use-toplevel  = [ "dep:arc-swap", "dep:wayland-client", "dep:wayland-protocols-wlr" ]

[profile.release]
lto       = true
opt-level = "z"
strip     = true
