name: Build with Cargo

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "src/**.rs", "Cargo.toml", "Cargo.lock"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build
        run: cargo build --verbose
