name: Build with Cargo

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "src/**.rs", "Cargo.toml", "Cargo.lock"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Format
        run: cargo fmt -- --check

      - name: Check
        run: cargo check

      - name: Test
        run: cargo test

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Check feature combinations
        run: |
          cargo check --no-default-features
          cargo check --no-default-features --features notifications
          cargo check --no-default-features --features encryption
          cargo check --no-default-features --features use-toplevel
